### PR TITLE
Updated Footer Fix Bug #144

### PR DESCRIPTION
**Pull request by whizzbbig**
## Describe your changes
Redesigned the footer
## Screenshots - If Any (Optional)
Screenshot 2565-10-15 at 4 26 20 PM

## Issue ticket number and link - If Any
#144 
## Checklist before requesting a review

- [x] I have performed a self-review of my code.

- [x] Followed the repository's [Contributing Guidelines](https://github.com/dvstechlabs/Noteslify/blob/main/CONTRIBUTING.md).

- [x] I ran the app and tested it locally to verify that it works as expected.

- [x] I have starred the repository.

### CODE REVIEW

**Review by devarshishimpi — CHANGES_REQUESTED** [review]
I chose random sizes, responsiveness issues 
image
image

Also, the font-size is too much. Could you reduce it as well?

image
Also, the previous bottom part in the above screenshot looked better, Could you revert it to that as well?

**Comment by whizzbbig** [comment]
@devarshishimpi i can see the social has been removed do want me to redesign and add them?

**Comment by devarshishimpi** [comment]
> @devarshishimpi i can see the social has been removed do you want me to redesign and add them?

I have only commented them, you just uncomment it.

**Comment by whizzbbig** [comment]
@devarshishimpi changes has been made as you requested talking about social you can uncomment they'll work the way you'll want

**Comment by whizzbbig** [comment]
@devarshishimpi done!! as you requested

**Review by devarshishimpi — CHANGES_REQUESTED** [review]
Changes requested were made correctly. 
image
Do check with all sizes

**Comment by whizzbbig** [comment]
> Changes requested were made correctly. image Do check with all sizes

https://user-images.githubusercontent.com/54703305/195997231-2f0d9434-12f9-4eec-a0f2-a1c1394dcd8a.mov

yep i checked the sizes its good to go

**Comment by whizzbbig** [comment]
done! @devarshishimpi  we good now?

**Review by devarshishimpi — APPROVED** [review]
Works!!

**Pull request merged**
