### PR TITLE
added placeholder

### PR DESCRIPTION
**Pull request by biswajit035**
I have added place holder to add note popup

AFTER

## Checklist before requesting a review

- [x] I have performed a self-review of my code.

- [x] Followed the repository's [Contributing Guidelines](https://github.com/dvstechlabs/Noteslify/blob/main/CONTRIBUTING.md).

- [x] I ran the app and tested it locally to verify that it works as expected.

- [x] I have starred the repository.

### CODE REVIEW

**Comment by devarshishimpi** [comment]
@biswajit035 Could you resolve the conflicts and complete the PR steps?

**Comment by biswajit035** [comment]
> @biswajit035 Could you resolve the conflicts and complete the PR steps?

Yes I have resolved that conflicts

**Comment by devarshishimpi** [comment]
> > @biswajit035 Could you resolve the conflicts and complete the PR steps?
> 
> Yes I have resolved that conflicts

image

**Comment by biswajit035** [comment]
> > > @biswajit035 Could you resolve the conflicts and complete the PR steps?
> > 
> > 
> > Yes I have resolved that conflicts
> 
> image



> > > @biswajit035 Could you resolve the conflicts and complete the PR steps?
> > 
> > 
> > Yes I have resolved that conflicts
> 
> image

I hope now I have done all the steps

**Review by devarshishimpi — APPROVED** [review]

**Pull request merged**
