### PR TITLE
Fix backend uri

### PR DESCRIPTION
**Pull request by nmathew98**
## Describe your changes
Issue: #93 

## Checklist before requesting a review

- [x] I have performed a self-review of my code.

- [x] Followed the repository's [Contributing Guidelines](/CONTRIBUTING.md).

- [x] I ran the app and tested it locally to verify that it works as expected.

- [x] I have starred the repository.

### CODE REVIEW

**Comment by nmathew98** [comment]
@devarshishimpi

**Comment by devarshishimpi** [comment]
> @devarshishimpi

If im not wrong, we need another dot env config for the URL right?

**Comment by devarshishimpi** [comment]
Ah okay, it's added to the production one.

**Comment by nmathew98** [comment]
> Ah okay, it's added to the production one.

So update to get the backend url from `process.env`?

**Comment by devarshishimpi** [comment]
> > Ah okay, it's added to the production one.
> 
> So update to get the backend url from `process.env`?

I'll make a PR for it in ur repo

**Comment by nmathew98** [comment]
> > > Ah okay, it's added to the production one.
> > 
> > 
> > So update to get the backend url from `process.env`?
> 
> I'll make a PR for it in ur repo

I can just do it, so complicated if not haha

**Comment by devarshishimpi** [comment]
> > > > Ah okay, it's added to the production one.
> > > 
> > > 
> > > So update to get the backend url from `process.env`?
> > 
> > 
> > I'll make a PR for it in ur repo
> 
> I can just do it, so complicated if not haha, what's the name of the config variable?

Not for the config variable,
Just replace this `? 'https://noteslify.vercel.app'`
with this `? 'productionurl'`

**Comment by nmathew98** [comment]
> productionurl



> > > > > Ah okay, it's added to the production one.
> > > > 
> > > > 
> > > > So update to get the backend url from `process.env`?
> > > 
> > > 
> > > I'll make a PR for it in ur repo
> > 
> > 
> > I can just do it, so complicated if not haha, what's the name of the config variable?
> 
> Not for the config variable, Just replace this `? 'https://noteslify.vercel.app'` with this `? 'productionurl'`

So it will be `process.env.PRODUCTIONURL` or `process.env.productionurl`

**Review by devarshishimpi — APPROVED** [review]
Okay, actually without the env, cause it's just a extra variable

**Comment by devarshishimpi** [comment]
I'll update that after merge

**Pull request merged**
