### PR TITLE
fixed issue-110 (added encryption of notes)

### PR DESCRIPTION
**Pull request by Gauravdarkslayer**
## Describe your changes
Added encryption while saving notes(title and description). And decryption while retrieving the notes .
## Issue ticket number and link - If Any
[ISSUE-110](https://github.com/dvstechlabs/Noteslify/issues/110)
## Checklist before requesting a review

- [x] I have performed a self-review of my code.

- [x] Followed the repository's [Contributing Guidelines](https://github.com/dvstechlabs/Noteslify/blob/main/CONTRIBUTING.md).

- [x] I ran the app and tested it locally to verify that it works as expected.

- [x] I have starred the repository.

### CODE REVIEW

**Comment by devarshishimpi** [comment]
@Gauravdarkslayer Could you complete the steps before review?
image

**Comment by Gauravdarkslayer** [comment]
Hi @devarshishimpi , Can you please let me know which version number is discussed over the `Contributing.md` file ? 
image



Is this the version number you are talking about ?
image
Currently its 1.3.5-beta

**Comment by devarshishimpi** [comment]
> Hi @devarshishimpi , Can you please let me know which version number is discussed over the `Contributing.md` file ? image
> 
> Is this the version number you are talking about ? image Currently its 1.3.5-beta

Yes, we'll take over the version number steps, you can complete rest of them.

**Comment by Gauravdarkslayer** [comment]
Okay so I've completed all others. Let me know if anything is pending from my end. Thank you !!

**Comment by devarshishimpi** [comment]
> Okay so I've completed all others. Let me know if anything is pending from my end. Thank you !! @devarshishimpi

Yes, I saw that. Will review the same.

**Review by devarshishimpi — COMMENTED** [review]
Not sure why but the notes are being stored in plain text in the MongoDB Database

**Comment by Gauravdarkslayer** [comment]
@devarshishimpi Can you please give some more details ? All the notes has been encrypted at my end. Is there any error in the console ? 
image


image

Please refer to these images once. 
Also notes will get decrypted while fetching from the database.

**Comment by Gauravdarkslayer** [comment]
Yes please do let me know. Thanks !!

**Comment by Gauravdarkslayer** [comment]
It's alright, thanks for reviewing !! :)

**Pull request merged**
