### PR TITLE
Footer made responsive

### PR DESCRIPTION
**Pull request by bhumika-1-3**
## Describe your changes
Footer UI improved and made responsive
## Issue ticket number and link - If Any
#104 
## Checklist before requesting a review

- [x] I have performed a self-review of my code.

- [x] Followed the repository's [Contributing Guidelines](https://github.com/dvstechlabs/Noteslify/blob/main/CONTRIBUTING.md).

- [x] I ran the app and tested it locally to verify that it works as expected.

- [x] I have starred the repository.

### CODE REVIEW

**Review by devarshishimpi — CHANGES_REQUESTED** [review]
Could you add `classname` instead of `class` ?? It's react based. So we don't want those warnings errors

**Comment by bhumika-1-3** [comment]
Done . 
It's Great working with you.

**Review by devarshishimpi — APPROVED** [review]
Yes, Thanks For Contributing!!

**Comment by devarshishimpi** [comment]
> Done . It's Great working with you.

You can contact me further at devarshishimpi@gmail.com if you want.

**Pull request merged**
