### PR TITLE
 update README.MD

### PR DESCRIPTION
**Pull request by Darkrider0007**
## Describe your changes
I update README.MD file, whenever you marge anyone's pull request it will automatically update.

## Screenshots - If Any (Optional)
image

## Checklist before requesting a review

- [x] I have performed a self-review of my code.

- [x] Followed the repository's [Contributing Guidelines](https://github.com/dvstechlabs/Noteslify/blob/main/CONTRIBUTING.md).

- [x] I ran the app and tested it locally to verify that it works as expected.

- [x] I have starred the repository.

### CODE REVIEW

**Comment by MrKrishnaAgarwal** [comment]
Is it required @devarshishimpi ?

**Comment by devarshishimpi** [comment]
@Darkrider0007 We do not plan on adding this as of now.

**Comment by devarshishimpi** [comment]
> Is it required @devarshishimpi ?

Nope, the readme is already too lengthy.

**Comment by MrKrishnaAgarwal** [comment]
> > Is it required @devarshishimpi ?
> 
> Nope, the readme is already too lengthy.

Yes 👍🏻

**Pull request closed without merging**
