### PR TITLE
Change password feature

### PR DESCRIPTION
**Pull request by shivamchourasia4**
## Screenshots - If Any (Optional)
Screenshot 2022-10-02 at 8 17 33 PM

## Checklist before requesting a review

- [x] I have performed a self-review of my code.

- [x] Followed the repository's [Contributing Guidelines](/CONTRIBUTING.md).

- [x] I ran the app and tested it locally to verify that it works as expected.

- [x] I have starred the repository.

### CODE REVIEW

**Comment by devarshishimpi** [comment]
@shivamchourasia4 The last tick won't work since it's not starred.

**Comment by shivamchourasia4** [comment]
> @shivamchourasia4 The last tick won't work since it's not starred.

Just did it.

**Review by abhinandanwadwa — CHANGES_REQUESTED** [review]
Do Recheck The Comment on Line number 442 in backend/routes/auth.js

**Comment by shivamchourasia4** [comment]
> Do Recheck The Comment on Line number 442 in backend/routes/auth.js

Fixed it. Might have overlooked that as I not used to writing comments at work.

**Review by devarshishimpi — APPROVED** [review]
LGTM

**Review by abhinandanwadwa — APPROVED** [review]

**Pull request merged**
