### PR TITLE
Fix issue #250 - LocalStorage 'theme' item not updated

### PR DESCRIPTION
**Pull request by JunDevHarsh**
## Describe your changes
- Created a custom hook called `useLocalStorage`
- Fix the issue #250
## Checklist before requesting a review

- [x] I have performed a self-review of my code.

- [x] Followed the repository's [Contributing Guidelines](https://github.com/dvstechlabs/Noteslify/blob/main/CONTRIBUTING.md).

- [x] I ran the app and tested it locally to verify that it works as expected.

- [x] I have starred the repository.

### CODE REVIEW

**Comment by devarshishimpi** [comment]
@JunDevHarsh Could you complete the review steps before reviewing the PR??

**Review by abhinandanwadwa — COMMENTED** [review]
image

Your code has changed the theme of the landing page.

Some Tips:
   1. Add some screen shots or a screen recording of visible changes (if any).
   2. Prefer single quotes ('  ') over double quotes ("  ") while contributing to this repository.

**Comment by devarshishimpi** [comment]
> image
> 
> Your code has changed the theme of the landing page.
> 
> Some Tips:
> 
> 1. Add some screen shots or a screen recording of visible changes (if any).
> 2. Prefer single quotes ('  ') over double quotes ("  ") while contributing to this repository.



> image
> 
> Your code has changed the theme of the landing page.
> 
> Some Tips:
> 
> 1. Add some screen shots or a screen recording of visible changes (if any).
> 2. Prefer single quotes ('  ') over double quotes ("  ") while contributing to this repository.

Those changes were made to the new `/frontendnew` folder, the `/frontend` is deprecated now. But yes, apart from that single quotes over double quotes is a valid issue along with screenshots.

**Review by devarshishimpi — APPROVED** [review]
LGTM!! Thanks For Contributing!! Minor Issues as commented by @abhinandanwadwa but overall looks good.

**Comment by JunDevHarsh** [comment]
Hello there, I apologize that I didn't share a screenshot or screen recording before making a PR. Here is the screen recording of the issue that I have faced and solved it.

Before issue: 

https://user-images.githubusercontent.com/94737463/208252301-1b193960-8680-474e-9d9a-31876a019c5c.mp4

###

After issue:

https://user-images.githubusercontent.com/94737463/208252387-53338212-9ed2-4c59-aaa2-fe66b2c191ca.mp4

**Comment by devarshishimpi** [comment]
> Hello there, I apologize that I didn't share a screenshot or screen recording before making a PR. Here is the screen recording of the issue that I have faced and solved it.
> 
> Before issue:
> 
>  before_bug.mp4 
> After issue:
> 
>  after_bug.mp4

It's fine!! Found out the issue as described in the PR and issue. Thanks For Contributing Again!! 🙌🏻

**Pull request merged**
