### PR TITLE
animations added

### PR DESCRIPTION
**Pull request by bhumika-1-3**
#106 

## Checklist before requesting a review

- [x] I have performed a self-review of my code.

- [x] Followed the repository's [Contributing Guidelines](/CONTRIBUTING.md).

- [x] I ran the app and tested it locally to verify that it works as expected.

- [x] I have starred the repository.

### CODE REVIEW

**Comment by devarshishimpi** [comment]
Closes https://github.com/dvstechlabs/Noteslify/issues/106

**Review by devarshishimpi — COMMENTED** [review]
Could you adjust the speeds of the 1st and 3rd mobile image? Instead of having all 3 move at the same speed. We could have them both at different speed and the 2nd at a different speed

**Comment by bhumika-1-3** [comment]
I have tried to add delay to the speeds and added more animations.

**Comment by bhumika-1-3** [comment]
If I set the speed of 1st and 3rd  same the animation of 3rd gets completed before it is visible.

**Comment by devarshishimpi** [comment]
> If I set the speed of 1st and 3rd same the animation of 3rd gets completed before it is visible.

Okay, I think you can revert to the previous commit and then done

**Comment by bhumika-1-3** [comment]
okay, Done. Thank you

**Review by devarshishimpi — APPROVED** [review]

**Pull request merged**
