### PR TITLE
added custom modal for confirmation

### PR DESCRIPTION
**Pull request by RakibRahman**
## Describe your changes
Added custom confirmation modal.
Implemented this modal for the following actions:
- Deleting account
- Deleting note

This modal can also be used to show components.

## Screenshots - If Any (Optional)
ss
ss
## Checklist before requesting a review

- [ x] I have performed a self-review of my code.

- [ x] Followed the repository's [Contributing Guidelines](https://github.com/dvstechlabs/Noteslify/blob/main/CONTRIBUTING.md).

- [ x] I ran the app and tested it locally to verify that it works as expected.

- [ x] I have starred the repository.

### CODE REVIEW

**Comment by RakibRahman** [comment]
@devarshishimpi  login/sign up button issue was persisting even before implementing the custom modal. I'll try to sort this out.

**Comment by RakibRahman** [comment]
@devarshishimpi login/signup button issue fixed. 
ss

**Comment by devarshishimpi** [comment]
> @devarshishimpi login/sign up button issue was persisting even before implementing the custom modal. I'll try to sort this out.

I see, didn't check with that

**Comment by devarshishimpi** [comment]
> @devarshishimpi login/signup button issue fixed. ss

Could you work with the username/email/password field as well?

**Comment by RakibRahman** [comment]
> > @devarshishimpi login/signup button issue fixed. ss
> 
> Could you work with the username/email/password field as well?

can you elaborate? what is the requirement?

**Comment by devarshishimpi** [comment]
image

Can you work on the fix for this?

**Comment by RakibRahman** [comment]
> image
> 
> Can you work on the fix for this?
Login and sign up form is working fine on my end.

**Comment by devarshishimpi** [comment]
> > image
> > Can you work on the fix for this?
> > The login and sign-up form is working fine on my end.
> > ss

Will check again

**Comment by RakibRahman** [comment]
Any updates on this PR?
If this gets PR gets accepted, I'll start working on issue #233

**Review by devarshishimpi — APPROVED** [review]
Perfect!! That issue with the login/singup page still not fixed but it's fine as it wasn't a part of this PR. And thanks for fixing the button. It's fixed now 🙌🏻 only the placeholders are still pending.

**Comment by devarshishimpi** [comment]
Can be a issue from my end too

**Comment by RakibRahman** [comment]
I checked again. found no issue related to placeholder/input from my end.

**Comment by devarshishimpi** [comment]
> I checked again. found no issue related to placeholder/input from my end.

I'll check in different browser again. Maybe an issue on my end. If it still persists. I'll raise an issue for it

**Pull request merged**
