### PR TITLE
Added responsive nav bar

### PR DESCRIPTION
**Pull request by EmmanuelAllanMJ**
## Describe your changes
Added responsive Nav Bar

## Screenshots - If Any (Optional)

image
nav resp final

## Issue ticket number and link - If Any
#168 

## Checklist before requesting a review

- [x] I have performed a self-review of my code.

- [x] Followed the repository's [Contributing Guidelines](https://github.com/dvstechlabs/Noteslify/blob/main/CONTRIBUTING.md).

- [x] I ran the app and tested it locally to verify that it works as expected.

- [ ] I have starred the repository.

### CODE REVIEW

**Comment by devarshishimpi** [comment]
@khushi818

**Comment by khushi818** [comment]
hello @EmmanuelAllanMJ you did some really good changes but you removed the close icon and  also the blur background in menu dropdown. Can you please correct that? . Also please sync your repo before doing changes so there is no merge conflict

**Comment by EmmanuelAllanMJ** [comment]
Sure, I'll make those changes

**Comment by EmmanuelAllanMJ** [comment]
@khushi818 Is this fine?
* Added close menu
* Added blur background to the menu dropdown
nav design added close btn 1

**Comment by khushi818** [comment]
@EmmanuelAllanMJ  yes it looks awesome, just send a pull request, we will further inform you.

**Pull request closed without merging**
