### PR TITLE
feat: Added Issue Templates (Form) 🛠

### LINKED ISSUE #46: Add Issues Templates

### PR DESCRIPTION
**Pull request by MrKrishnaAgarwal**
## Describe your changes
Same as Title

## Issue ticket number and link - If Any
Closes #46 

## Checklist before requesting a review

- [x] I have performed a self-review of my code.

- [x] Followed the repository's [Contributing Guidelines](https://github.com/dvstechlabs/Noteslify/blob/main/CONTRIBUTING.md).

- [x] I ran the app and tested it locally to verify that it works as expected.

- [x] I have starred the repository.

## Additional Information (Optional)
NA

### CODE REVIEW

**Review by devarshishimpi — APPROVED** [review]
Are there any labels to be added @MrKrishnaAgarwal ?

**Comment by devarshishimpi** [comment]
@MrKrishnaAgarwal Starring does help the repository 😄 You may complete the last tick

**Comment by MrKrishnaAgarwal** [comment]
Done 🌟

I did that before I guess.
done now :)

check discord pls

**Comment by MrKrishnaAgarwal** [comment]
@devarshishimpi

**Comment by devarshishimpi** [comment]
> Done 🌟
> 
> I did that before I guess. done now :)
> 
> check discord pls

Yes checking

**Comment by devarshishimpi** [comment]
> Are there any labels to be added @MrKrishnaAgarwal ?

@MrKrishnaAgarwal Labels??? Newly to be added?

**Comment by MrKrishnaAgarwal** [comment]
> > Are there any labels to be added @MrKrishnaAgarwal ?
> 
> @MrKrishnaAgarwal Labels??? Newly to be added?

Yes, Sent you on discord

**Comment by devarshishimpi** [comment]
> > > Are there any labels to be added @MrKrishnaAgarwal ?
> > 
> > 
> > @MrKrishnaAgarwal Labels??? Newly to be added?
> 
> Yes, Sent you on discord

Okay

**Pull request merged**
