### PR TITLE
Added Pull Request Template 👨‍💻

### LINKED ISSUE #58: chore: Add Pull Request Template
Let's add PR Template to this repository

### PR DESCRIPTION
**Pull request by MrKrishnaAgarwal**
cc @devarshishimpi

closes #58

Added PR Template in .github directory :)

### CODE REVIEW

**Review by devarshishimpi — APPROVED** [review]

**Comment by devarshishimpi** [comment]
I don't think this PR has too many changes for Hacktoberfest.

**Comment by devarshishimpi** [comment]
@MrKrishnaAgarwal Is there an option for Github Forms on PR Templates as well?

**Comment by devarshishimpi** [comment]
If so, you can make a new PR for the same with the changes. It will be added as part of Hacktoberfest as well.

**Comment by MrKrishnaAgarwal** [comment]
> @MrKrishnaAgarwal Is there an option for Github Forms on PR Templates as well?

This is a pr template only that I made
I don't know about github forms
Are you talking about issue forms?

**Comment by devarshishimpi** [comment]
> > @MrKrishnaAgarwal Is there an option for Github Forms on PR Templates as well?
> 
> This is a pr template only that I made I don't know about github forms Are you talking about issue forms?

Yes, issue forms. But, Can they be applied for PRs as well?

**Comment by MrKrishnaAgarwal** [comment]
> > > @MrKrishnaAgarwal Is there an option for Github Forms on PR Templates as well?
> > 
> > This is a pr template only that I made I don't know about github forms Are you talking about issue forms?
> 
> Yes, issue forms. But, Can they be applied for PRs as well?

No, it's a beta feature only for issues

**Comment by devarshishimpi** [comment]
This PR is made part of Hacktoberfest

**Comment by devarshishimpi** [comment]
> > > > @MrKrishnaAgarwal Is there an option for Github Forms on PR Templates as well?
> > > 
> > > 
> > > This is a pr template only that I made I don't know about github forms Are you talking about issue forms?
> > 
> > 
> > Yes, issue forms. But, Can they be applied for PRs as well?
> 
> No, it's a beta feature only for issues

Yep okay, then this works.

**Comment by MrKrishnaAgarwal** [comment]
Thanks a lot 🤩

**Pull request merged**
