### PR TITLE
Add ability to search for notes

### PR DESCRIPTION
**Pull request by nmathew98**
## Describe your changes

Issue: https://github.com/dvstechlabs/Noteslify/issues/54
Added NotesContext on the frontend, and search notes route on the backend. The filtered list of notes is held in the context. If no search text is provided, all notes are fetched if there is a search text then we get the filtered list.

## Checklist before requesting a review

- [x] I have performed a self-review of my code.

- [x] Followed the repository's [Contributing Guidelines](/CONTRIBUTING.md).

- [x] I ran the app and tested it locally to verify that it works as expected.

- [x] I have starred the repository.

## Additional Information (Optional)

### CODE REVIEW

**Comment by nmathew98** [comment]
@devarshishimpi Can't seem to assign you to this

**Comment by devarshishimpi** [comment]
> this

Done, will review in sometime

**Review by devarshishimpi — COMMENTED** [review]
@nmathew98 Interesting. Not sure what was added there like enhancement, since yes, Seach for notes did get merged by @abhinandanwadwa . Is there any sort of enhancement over the current search code? Or, could you elaborate your PR since search functionality did get added

Also, I see some merge conflicts in the packagejson file.

**Comment by nmathew98** [comment]
> @nmathew98 Interesting. Not sure what was added there like enhancement, since yes, Seach for notes did get merged by @abhinandanwadwa . Is there any sort of enhancement over the current search code? Or, could you elaborate your PR since search functionality did get added
> 
> Also, I see some merge conflicts in the packagejson file.

No actual improvement in terms of functionality to be honest haha, was just looking for the Hacktoberfest PR. Ah sorry about the merge conflicts in `package-lock.json`. Feel free to close if not needed, I think the NotesProvider is an improvement since it centralises the logic for adding notes but other than that nothing much

**Review by devarshishimpi — APPROVED** [review]

**Comment by devarshishimpi** [comment]
@nmathew98 The previous one had some bugs, looks like this one fixes it as well!! Valid Contribution!!! Thank You!!!

**Comment by nmathew98** [comment]
Ah ok, that's great to hear, thanks very much! :D

**Pull request merged**
