### PR TITLE
Add Recycle Bin Functionality (#35)

### PR DESCRIPTION
**Pull request by abhinandanwadwa**

### CODE REVIEW

**Comment by devarshishimpi** [comment]
@abhinandanwadwa Kindly merge the PR I have made in your fork.

**Review by devarshishimpi — APPROVED** [review]

**Comment by devarshishimpi** [comment]
@khushi818 Take your time reviewing. If there are any changes to be made. Please let us know.

**Comment by khushi818** [comment]
It has css problem. Give form a class then merge it. Don't use direct tags. change for form header and other tags you used. Give them a class name. @abhinandanwadwa  @devarshishimpi

**Review by khushi818 — COMMENTED** [review]
Change the CSS

**Comment by devarshishimpi** [comment]
> It has css problem. Give form a class then merge it. Don't use direct tags. change for form header and other tags you used. Give them a class name. @abhinandanwadwa @devarshishimpi

Will be done 👍🏻

**Pull request merged**
