### PR TITLE
updated README file (contributing section)

### PR DESCRIPTION
**Pull request by RakibRahman**
## Checklist before requesting a review

- [x] I have performed a self-review of my code.

- [x] Followed the repository's [Contributing Guidelines](https://github.com/dvstechlabs/Noteslify/blob/main/CONTRIBUTING.md).

- [x] I ran the app and tested it locally to verify that it works as expected.

- [x] I have starred the repository.

### CODE REVIEW

**Comment by devarshishimpi** [comment]
Kindly complete all the steps and raise an issue before creating PR.

**Comment by RakibRahman** [comment]
completed all the steps and raised an issue. Kindly review the PR

**Review by MrKrishnaAgarwal — APPROVED** [review]
Okay!
Thanks for contributing 🌟

**Comment by MrKrishnaAgarwal** [comment]
Hey @RakibRahman,
Can you edit the in the same way, Code of Conduct in the readme?

**Comment by RakibRahman** [comment]
@MrKrishnaAgarwal Sure. Do I have to raise a new issue for it?

**Comment by MrKrishnaAgarwal** [comment]
> @MrKrishnaAgarwal Sure. Do I have to raise a new issue for it?

No, it's fine.
You can mention that in the previous issue and in this PR.
Go ahead 🙂

**Review by devarshishimpi — APPROVED** [review]
Great!! Thanks For Contributing!!

**Review by MrKrishnaAgarwal — APPROVED** [review]

**Pull request merged**
