### PR TITLE
Fixed page load login issue

### PR DESCRIPTION
**Pull request by IncredibleZuess**
## Describe your changes
I added an async/await in the /backend/middleware/fetchuser.js when fetching the jsonwebtoken
## Screenshots - If Any (Optional)
N/A
## Issue ticket number and link - If Any
fixes: #108 
## Checklist before requesting a review

- [x] I have performed a self-review of my code.

- [x] Followed the repository's [Contributing Guidelines](/CONTRIBUTING.md).

- [x] I ran the app and tested it locally to verify that it works as expected.

- [x] I have starred the repository.

## Additional Information (Optional)
This is a really small fix using an async and await before requesting the user's auth token

### CODE REVIEW

**Review by devarshishimpi — APPROVED** [review]

**Comment by devarshishimpi** [comment]
@IncredibleZuess Doesn't look fixed yet

**Comment by IncredibleZuess** [comment]
@devarshishimpi Interesting. I was sure that was the issue. Do you get any errors saying jwt is malformed?

**Comment by devarshishimpi** [comment]
There
image

**Comment by devarshishimpi** [comment]
Goes blank after login, in notes section and needs a refresh

**Comment by IncredibleZuess** [comment]
Alright! 
Yeah sure no problem. 
Quite interesting that it gives that error now...
I'll write up a fix real quick then submit a PR :)

**Comment by devarshishimpi** [comment]
> Alright! Yeah sure no problem. Quite interesting that it gives that error now... I'll write up a fix real quick then submit a PR :)

Sure

**Pull request merged**
