### PR TITLE
Max-width fixes in landing page

### PR DESCRIPTION
**Pull request by nirajpdn**
## Describe your changes
Added global styles for max-width.
Fix max-width in all sections of landing page.

### Navbar
Screen Shot 2022-10-29 at 06 16 50

### Footer
Screen Shot 2022-10-29 at 06 17 08

## Issue ticket number and link - If Any
Issue #186 

## Checklist before requesting a review

- [x] I have performed a self-review of my code.

- [x] Followed the repository's [Contributing Guidelines](https://github.com/dvstechlabs/Noteslify/blob/main/CONTRIBUTING.md).

- [x] I ran the app and tested it locally to verify that it works as expected.

- [x] I have starred the repository.

### CODE REVIEW

**Comment by nirajpdn** [comment]
@devarshishimpi please review the changes. Thank you.

**Review by devarshishimpi — COMMENTED** [review]
Could you specify the device size you have added screenshots for??

**Comment by nirajpdn** [comment]
> Could you specify the device size you have added screenshots for??

@devarshishimpi , You can see the changes in your screen just by decreasing zoom of the browser.

**Comment by devarshishimpi** [comment]
Not a necessary change

**Pull request closed without merging**
