### PR TITLE
Ensure Mongo is connected first before everything

### PR DESCRIPTION
**Pull request by nmathew98**
## Describe your changes
Ensure Mongo connection is established before anything and retry if connection fails

The source of buffering timed out seems to be the connection, I think this will fix it

Related: https://www.mongodb.com/community/forums/t/mongooseerror-operation-users-insertone-buffering-timed-out-after-10000ms/143993

## Checklist before requesting a review

- [x] I have performed a self-review of my code.

- [x] Followed the repository's [Contributing Guidelines](/CONTRIBUTING.md).

- [x] I ran the app and tested it locally to verify that it works as expected.

- [x] I have starred the repository.

### CODE REVIEW

**Review by devarshishimpi — APPROVED** [review]
Interesting. The code looks well, I hope this fixes it in production.

**Comment by devarshishimpi** [comment]
@nmathew98 It fixed everything including login and all pages of recycle bin and account reset password. But now it's stuck on the notes page. Navigating to other pages works exactly fine.
image

**Comment by nmathew98** [comment]
> @nmathew98 It fixed everything including login and all pages of recycle bin and account reset password. But now it's stuck on the notes page. Navigating to other pages works exactly fine. image

Ah ok this is a CORS issue I think

**Comment by devarshishimpi** [comment]
Also, have shifted the domain name here https://noteslify.stonecss.com
The new changes are running in production.

**Comment by devarshishimpi** [comment]
> > @nmathew98 It fixed everything including login and all pages of recycle bin and account reset password. But now it's stuck on the notes page. Navigating to other pages works exactly fine. image
> 
> Ah ok this is a CORS issue I think

Could you help with the fix faster since it's running in production?

**Pull request merged**
