### PR TITLE
feat: add pricing page

### LINKED ISSUE #206: Adding Pricing Page

### PR DESCRIPTION
**Pull request by Dun-sin**
## Describe your changes
- add pricing page to router
- created pricing page

## Screenshots - If Any (Optional)
image

## Issue ticket number and link - If Any
closes #206 

## Checklist before requesting a review

- [x] I have performed a self-review of my code.

- [x] Followed the repository's [Contributing Guidelines](https://github.com/dvstechlabs/Noteslify/blob/main/CONTRIBUTING.md).

- [x] I ran the app and tested it locally to verify that it works as expected.

- [ ] I have starred the repository.

### CODE REVIEW

**Review by devarshishimpi — CHANGES_REQUESTED** [review]
Could we have a better UI for the same?

Like having some description fields and better spacing.
As well as reducing the white space. Just to name a few.

**Comment by Dun-sin** [comment]
> Could we have a better UI for the same?
> 
> Like having some description fields and better spacing. As well as reducing the white space. Just to name a few.

We will keep going back and forth and waste time, unless you give me a UI design you want me to work with or merge this in a test branch and adjust it yourself

**Comment by devarshishimpi** [comment]
> > Could we have a better UI for the same?
> > Like having some description fields and better spacing. As well as reducing the white space. Just to name a few.
> 
> We will keep going back and forth and waste time, unless you give me a UI design you want me to work with or merge this in a test branch and adjust it yourself

Have provided similar design in the issue itself

**Comment by Dun-sin** [comment]
> Have provided similar design in the issue itself

i know and i followed it, and you still don't like it, hence i said “exactly” what you want and not similar

**Comment by devarshishimpi** [comment]
> > Have provided similar design in the issue itself
> 
> i know and i followed it, and you still don't like it, hence i said “exactly” what you want and not similar

Will Provide you with a Figma file soon

**Comment by Dun-sin** [comment]
> Will Provide you with a Figma file soon

Awesome, thank you

**Comment by devarshishimpi** [comment]
> > Will Provide you with a Figma file soon
> 
> Awesome, thank you

We are shifting the frontend landing page to tailwind.  So like is it fine if we close this PR since the new pricing page would be based on tailwind??

( Yet to add the new landing page folder, but will be added soon )

**Comment by Dun-sin** [comment]
> > > Will Provide you with a Figma file soon
> > 
> > 
> > Awesome, thank you
> 
> We are shifting the frontend landing page to tailwind. So like is it fine if we close this PR since the new pricing page would be based on tailwind?? Sorry for the inconvenience caused.
> 
> ( Yet to add the new landing page folder, but will be added soon )

alright, let me know if you need my help in anything

**Comment by devarshishimpi** [comment]
> > > > Will Provide you with a Figma file soon
> > > 
> > > 
> > > Awesome, thank you
> > 
> > 
> > We are shifting the frontend landing page to tailwind. So like is it fine if we close this PR since the new pricing page would be based on tailwind?? Sorry for the inconvenience caused.
> > ( Yet to add the new landing page folder, but will be added soon )
> 
> alright, let me know if you need my help in anything

Sure

**Pull request closed without merging**
