### PR TITLE
Add custom NewsLetter section

### PR DESCRIPTION
**Pull request by pedropcamellon**
## Describe your changes
1. Add global style rules.
2. Add custom Newsletter section.

## Screenshots - If Any (Optional)
*Mobile*
image

*Desktop*
image

## Issue ticket number and link - If Any
[#102]

## Checklist before requesting a review
- [X] I have performed a self-review of my code.
- [X] Followed the repository's [Contributing Guidelines](https://github.com/dvstechlabs/Noteslify/blob/main/CONTRIBUTING.md).
- [X] I ran the app and tested it locally to verify that it works as expected.
- [X] I have starred the repository.

### CODE REVIEW

**Comment by devarshishimpi** [comment]
Maybe merging the main branch at the last caused it

**Comment by pedropcamellon** [comment]
It's commented. See "Comment NewsLetter section component in homepage" commit. Uncomment the component in Home.js

**Comment by devarshishimpi** [comment]
@pedropcamellon I can still see the older form. Could you rewrite/copy-paste the code for the new design?

**Comment by pedropcamellon** [comment]
I made a new pull req

**Pull request closed without merging**
